appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: jyccXM3fhVji8sMwJlW71vT97n6ES8M1+xejqBeL0CHCXneg9WXnXJEKVv3ijE6hXq/aJmweN5A526f8xjzKhDS1CnVtAYx2aPHC2IQnt/s7b7ju/eFohwdW9CQlsTk7pRrMBl10GQ4eEypYMqSmMBN8R0+Z0dvHkR54wRXgSHdhipyCe1FOXMAUu1oRjf3tAu/3gfUNS4WwZAWZZWpWch5jFXdgcBVWcH6f9enLx6ucRQl2OsoUaACIU9FUTLVBtKz8PpEgzvtfaI6k1Erotyz7JR9swLGv/EsgIHuDNatBDJG5zqsOEqD6RvRWWi3SNY2aLxNfWffwjmVseVOLqexq471TRXt4YTu1+61qr/DtSgyUgREnx8j6mzZ4DfxqvI80kCoGNOOsmL9sD0q88jY4y1ZT/z741khlJ6wM/FmSYO0e/eRAvSSgScCgsYqt35QD74eZbI/suh/HXic62TzEyEn2yCOVdWg0iGS8GS4Nh7HYpsuGzXM1Tw2JKSa/DfzoJTbZxlA41pl+qXendGNS8HKyNr8yZQ/PoG4tJT+Relpsx+uS7N0HkA6apltYMiDJ5MLplKX7BkC4Doocy+0g1/G5cEtPYB4/oDVpyMEIx1qTcnKsdeoHcbhS6sW2HbarhLSI5XSh6qTLXenBxkaNgLN6CDn5VbU71aYArs4=
conda_forge_output_validation: true
